apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgB9AZXRNmtdeZRCaT4okMEZdnEbHdoPCZqpQ82zPFDoNoWyqFYJi0jNENddJlhn/qwtYoQ7JF7mU34YQT0D97s9MnzZFrbviwXQh4JbWfRylb0YmzUohRdnqFAtDcDrrntB8sd/JK/ZYz5WwP9geJF71LQxhEytv6/iB6MKQoIAU0fIiUJMGLjjVLBfvbiirumHlv9d6aTF3dqTShL+8+t/Oy4i+/YajVe0LJ9dvzOa9tZVFIiImbNMUHUtN+5WN6NeLgRY9EvRhAMiX+8kTjGPTpdYPzRUF6YfmclzdkukO5m4NQEPLDnMeQ6dspmX4mBWkH7vTEMCp9EnEyR9nnvgumPlicRwfyvROio0bzjiQ9bMKvTTpEK1omvqlZ8OiIVQn1+xDyrhcRAHJXXwGo0fgss71Wr9vUc3lODx91Vc12EEsaz9m0OjOp7Qyw4Wj9YVK3tdfWQSWRiqsLIutOXok61uDBihKU0HWN47Yh4tBmJQPbVp7I3A6KrSQ1DSEE4HXLuDFkM730ZgVeIRssjcyeVTxpQjVD3jDCoQZBSUf9BZy86TRMIJQS1POV8phDHrq/UQSLxn/ogOVMYvUEhtijcMs513NegMQJmVsrN03lm0yoRt2oGrFASBftnjIvKWmJCYB+goGeR0/nvEgfUxhDOf8CK9hPGHYhxVuj6pu/kTgjeTSDLjH9bK27vUTPQ6PRKn
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

